project_id = "vysrhwytayytcqnwdhwv"

[functions.push-to-padelpix]
verify_jwt = false

[functions.extract-location]
verify_jwt = false

[functions.api-get-clubs]
verify_jwt = false

[functions.api-update-clubs]
verify_jwt = false

[functions.enrich-organization]
verify_jwt = false

[functions.enrich-club]
verify_jwt = false

[functions.get-enrichment-status]
verify_jwt = false

[functions.enrich-person]
verify_jwt = false

[functions.normalize-data]
verify_jwt = false
